# Generated by Django 6.0.3 on 2026-03-23 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click')], max_length=10, verbose_name='Провайдер')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('waiting', 'В обработке'), ('paid', 'Оплачен'), ('cancelled', 'Отменён'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('amount', models.BigIntegerField(verbose_name='Сумма (тийин)')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID транзакции')),
                ('provider_time', models.BigIntegerField(blank=True, null=True, verbose_name='Время (ms)')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='Данные запроса')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Данные ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
