# Generated by Django 6.0.3 on 2026-03-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner_video_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='hero/', verbose_name='Изображение (обязательно)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(blank=True, upload_to='hero/', verbose_name='Изображение для мобильных'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, help_text='Видео играет на десктопе. На мобильных — фото.', upload_to='hero/videos/', verbose_name='Видео (MP4/WebM)'),
        ),
    ]
