# Generated by Django 6.0.3 on 2026-03-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_telegram_id_user_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uz', "O'zbek"), ('en', 'English')], default='ru', max_length=5, verbose_name='Язык'),
        ),
    ]
