# Generated by Django 6.0.3 on 2026-03-24 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('city', models.CharField(default='Ташкент', max_length=100, verbose_name='Город')),
                ('working_hours', models.CharField(blank=True, help_text='Например: Пн–Пт 9:00–19:00', max_length=100, verbose_name='Часы работы')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Пункт выдачи',
                'verbose_name_plural': 'Пункты выдачи',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('courier', 'Доставка курьером'), ('pickup', 'Самовывоз из пункта выдачи')], default='courier', max_length=20, verbose_name='Способ получения'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.pickuppoint', verbose_name='Пункт выдачи'),
        ),
    ]
