# Generated by Django 6.0.3 on 2026-03-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_is_active_alter_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('women', 'Женская'), ('men', 'Мужская'), ('kids', 'Детская'), ('unisex', 'Унисекс')], db_index=True, default='unisex', max_length=10, verbose_name='Раздел'),
        ),
    ]
