# Generated by Django 6.0.3 on 2026-03-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_favorite_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Одобрен'),
        ),
    ]
